-- Comprehensive ICD-10 codes for ENT clinic
-- Source: WHO ICD-10 Classification, Indonesian translation

-- Clear existing data (optional, only if reseeding)
-- DELETE FROM icd10_codes;

-- EAR DISEASES (H60-H95)
INSERT INTO icd10_codes (code, name_en, name_id, category, is_active) VALUES
-- External ear
('H60.0', 'Abscess of external ear', 'Abses telinga luar', 'Ear', true),
('H60.1', 'Cellulitis of external ear', 'Selulitis telinga luar', 'Ear', true),
('H60.2', 'Malignant otitis externa', 'Otitis eksterna maligna', 'Ear', true),
('H60.3', 'Other infective otitis externa', 'Otitis eksterna infektif lainnya', 'Ear', true),
('H60.4', 'Cholesteatoma of external ear', 'Kolesteatoma telinga luar', 'Ear', true),
('H60.5', 'Acute otitis externa, noninfective', 'Otitis eksterna akut non-infektif', 'Ear', true),
('H60.8', 'Other otitis externa', 'Otitis eksterna lainnya', 'Ear', true),
('H60.9', 'Otitis externa, unspecified', 'Otitis eksterna tidak spesifik', 'Ear', true),
('H61.0', 'Perichondritis of external ear', 'Perikondritis telinga luar', 'Ear', true),
('H61.1', 'Noninfective disorders of pinna', 'Gangguan non-infektif daun telinga', 'Ear', true),
('H61.2', 'Impacted cerumen', 'Serumen obturans', 'Ear', true),
('H61.3', 'Acquired stenosis of external ear canal', 'Stenosis liang telinga didapat', 'Ear', true),
('H61.8', 'Other specified disorders of external ear', 'Gangguan telinga luar spesifik lainnya', 'Ear', true),
('H61.9', 'Disorder of external ear, unspecified', 'Gangguan telinga luar tidak spesifik', 'Ear', true),

-- Middle ear and mastoid
('H65.0', 'Acute serous otitis media', 'Otitis media serosa akut', 'Ear', true),
('H65.1', 'Other acute nonsuppurative otitis media', 'Otitis media non-supuratif akut lainnya', 'Ear', true),
('H65.2', 'Chronic serous otitis media', 'Otitis media serosa kronik', 'Ear', true),
('H65.3', 'Chronic mucoid otitis media', 'Otitis media mukoid kronik', 'Ear', true),
('H65.4', 'Other chronic nonsuppurative otitis media', 'Otitis media non-supuratif kronik lainnya', 'Ear', true),
('H65.9', 'Nonsuppurative otitis media, unspecified', 'Otitis media non-supuratif tidak spesifik', 'Ear', true),
('H66.0', 'Acute suppurative otitis media', 'Otitis media supuratif akut', 'Ear', true),
('H66.1', 'Chronic tubotympanic suppurative otitis media', 'Otitis media supuratif tubotimpanik kronik', 'Ear', true),
('H66.2', 'Chronic atticoantral suppurative otitis media', 'Otitis media supuratif atikoantral kronik', 'Ear', true),
('H66.3', 'Other chronic suppurative otitis media', 'Otitis media supuratif kronik lainnya', 'Ear', true),
('H66.4', 'Suppurative otitis media, unspecified', 'Otitis media supuratif tidak spesifik', 'Ear', true),
('H66.9', 'Otitis media, unspecified', 'Otitis media tidak spesifik', 'Ear', true),
('H67.0', 'Otitis media in bacterial diseases', 'Otitis media pada penyakit bakterial', 'Ear', true),
('H67.1', 'Otitis media in viral diseases', 'Otitis media pada penyakit viral', 'Ear', true),
('H68.0', 'Eustachian salpingitis', 'Salpingitis tuba Eustachius', 'Ear', true),
('H68.1', 'Obstruction of Eustachian tube', 'Obstruksi tuba Eustachius', 'Ear', true),
('H69.0', 'Patulous Eustachian tube', 'Tuba Eustachius patulous', 'Ear', true),
('H69.8', 'Other specified disorders of Eustachian tube', 'Gangguan tuba Eustachius spesifik lainnya', 'Ear', true),
('H70.0', 'Acute mastoiditis', 'Mastoiditis akut', 'Ear', true),
('H70.1', 'Chronic mastoiditis', 'Mastoiditis kronik', 'Ear', true),
('H70.2', 'Petrositis', 'Petrositis', 'Ear', true),
('H70.8', 'Other mastoiditis and related conditions', 'Mastoiditis dan kondisi terkait lainnya', 'Ear', true),
('H70.9', 'Mastoiditis, unspecified', 'Mastoiditis tidak spesifik', 'Ear', true),
('H71.0', 'Cholesteatoma of attic', 'Kolesteatoma atik', 'Ear', true),
('H71.1', 'Cholesteatoma of tympanum', 'Kolesteatoma timpanum', 'Ear', true),
('H71.2', 'Cholesteatoma of mastoid', 'Kolesteatoma mastoid', 'Ear', true),
('H71.3', 'Diffuse cholesteatosis', 'Kolesteatosis difus', 'Ear', true),
('H71.9', 'Cholesteatoma, unspecified', 'Kolesteatoma tidak spesifik', 'Ear', true),
('H72.0', 'Central perforation of tympanic membrane', 'Perforasi sentral membran timpani', 'Ear', true),
('H72.1', 'Attic perforation of tympanic membrane', 'Perforasi atik membran timpani', 'Ear', true),
('H72.2', 'Other marginal perforations of tympanic membrane', 'Perforasi marginal membran timpani lainnya', 'Ear', true),
('H72.8', 'Other perforations of tympanic membrane', 'Perforasi membran timpani lainnya', 'Ear', true),
('H72.9', 'Perforation of tympanic membrane, unspecified', 'Perforasi membran timpani tidak spesifik', 'Ear', true),
('H73.0', 'Acute myringitis', 'Miringitis akut', 'Ear', true),
('H73.1', 'Chronic myringitis', 'Miringitis kronik', 'Ear', true),
('H73.8', 'Other specified disorders of tympanic membrane', 'Gangguan membran timpani spesifik lainnya', 'Ear', true),
('H73.9', 'Disorder of tympanic membrane, unspecified', 'Gangguan membran timpani tidak spesifik', 'Ear', true),
('H74.0', 'Tympanosclerosis', 'Timpanosklerosis', 'Ear', true),
('H74.1', 'Adhesive middle ear disease', 'Penyakit telinga tengah adhesif', 'Ear', true),
('H74.2', 'Discontinuity and dislocation of ear ossicles', 'Diskontinuitas dan dislokasi osikel', 'Ear', true),
('H74.3', 'Other acquired abnormalities of ear ossicles', 'Kelainan osikel didapat lainnya', 'Ear', true),
('H74.4', 'Polyp of middle ear', 'Polip telinga tengah', 'Ear', true),
('H74.8', 'Other specified disorders of middle ear and mastoid', 'Gangguan telinga tengah dan mastoid spesifik lainnya', 'Ear', true),
('H74.9', 'Disorder of middle ear and mastoid, unspecified', 'Gangguan telinga tengah dan mastoid tidak spesifik', 'Ear', true),

-- Inner ear diseases
('H80.0', 'Otosclerosis involving oval window, nonobliterative', 'Otosklerosis jendela oval non-obliteratif', 'Ear', true),
('H80.1', 'Otosclerosis involving oval window, obliterative', 'Otosklerosis jendela oval obliteratif', 'Ear', true),
('H80.2', 'Cochlear otosclerosis', 'Otosklerosis koklea', 'Ear', true),
('H80.8', 'Other otosclerosis', 'Otosklerosis lainnya', 'Ear', true),
('H80.9', 'Otosclerosis, unspecified', 'Otosklerosis tidak spesifik', 'Ear', true),
('H81.0', 'Ménière disease', 'Penyakit Meniere', 'Ear', true),
('H81.1', 'Benign paroxysmal vertigo', 'Vertigo paroksismal jinak', 'Ear', true),
('H81.2', 'Vestibular neuronitis', 'Neuronitis vestibular', 'Ear', true),
('H81.3', 'Other peripheral vertigo', 'Vertigo perifer lainnya', 'Ear', true),
('H81.4', 'Vertigo of central origin', 'Vertigo sentral', 'Ear', true),
('H81.8', 'Other disorders of vestibular function', 'Gangguan fungsi vestibular lainnya', 'Ear', true),
('H81.9', 'Disorder of vestibular function, unspecified', 'Gangguan fungsi vestibular tidak spesifik', 'Ear', true),
('H83.0', 'Labyrinthitis', 'Labirintitis', 'Ear', true),
('H83.1', 'Labyrinthine fistula', 'Fistula labirintus', 'Ear', true),
('H83.2', 'Labyrinthine dysfunction', 'Disfungsi labirintus', 'Ear', true),
('H83.3', 'Noise effects on inner ear', 'Efek kebisingan pada telinga dalam', 'Ear', true),

-- Hearing loss
('H90.0', 'Conductive hearing loss, bilateral', 'Tuli konduktif bilateral', 'Ear', true),
('H90.1', 'Conductive hearing loss, unilateral', 'Tuli konduktif unilateral', 'Ear', true),
('H90.2', 'Conductive hearing loss, unspecified', 'Tuli konduktif tidak spesifik', 'Ear', true),
('H90.3', 'Sensorineural hearing loss, bilateral', 'Tuli sensorineural bilateral', 'Ear', true),
('H90.4', 'Sensorineural hearing loss, unilateral', 'Tuli sensorineural unilateral', 'Ear', true),
('H90.5', 'Sensorineural hearing loss, unspecified', 'Tuli sensorineural tidak spesifik', 'Ear', true),
('H90.6', 'Mixed conductive and sensorineural hearing loss, bilateral', 'Tuli campuran bilateral', 'Ear', true),
('H90.7', 'Mixed conductive and sensorineural hearing loss, unilateral', 'Tuli campuran unilateral', 'Ear', true),
('H90.8', 'Mixed conductive and sensorineural hearing loss, unspecified', 'Tuli campuran tidak spesifik', 'Ear', true),
('H91.0', 'Ototoxic hearing loss', 'Tuli ototoksik', 'Ear', true),
('H91.1', 'Presbycusis', 'Presbiakusis', 'Ear', true),
('H91.2', 'Sudden idiopathic hearing loss', 'Tuli mendadak idiopatik', 'Ear', true),
('H91.3', 'Deaf mutism, not elsewhere classified', 'Tuli bisu', 'Ear', true),
('H91.8', 'Other specified hearing loss', 'Tuli spesifik lainnya', 'Ear', true),
('H91.9', 'Hearing loss, unspecified', 'Tuli tidak spesifik', 'Ear', true),
('H92.0', 'Otalgia', 'Otalgia (nyeri telinga)', 'Ear', true),
('H92.1', 'Otorrhoea', 'Otorea (keluar cairan telinga)', 'Ear', true),
('H92.2', 'Otorrhagia', 'Otoragia (perdarahan telinga)', 'Ear', true),
('H93.0', 'Degenerative and vascular disorders of ear', 'Gangguan degeneratif dan vaskular telinga', 'Ear', true),
('H93.1', 'Tinnitus', 'Tinitus (telinga berdenging)', 'Ear', true),
('H93.2', 'Other abnormal auditory perceptions', 'Persepsi auditori abnormal lainnya', 'Ear', true),
('H93.3', 'Disorders of acoustic nerve', 'Gangguan nervus akustik', 'Ear', true),

-- NOSE AND NASAL SINUS DISEASES (J30-J39)
-- Rhinitis
('J30.0', 'Vasomotor rhinitis', 'Rinitis vasomotor', 'Nose', true),
('J30.1', 'Allergic rhinitis due to pollen', 'Rinitis alergi karena polen', 'Nose', true),
('J30.2', 'Other seasonal allergic rhinitis', 'Rinitis alergi musiman lainnya', 'Nose', true),
('J30.3', 'Other allergic rhinitis', 'Rinitis alergi lainnya', 'Nose', true),
('J30.4', 'Allergic rhinitis, unspecified', 'Rinitis alergi tidak spesifik', 'Nose', true),
('J31.0', 'Chronic rhinitis', 'Rinitis kronik', 'Nose', true),
('J31.1', 'Chronic nasopharyngitis', 'Nasofaringitis kronik', 'Nose', true),
('J32.0', 'Chronic maxillary sinusitis', 'Sinusitis maksilaris kronik', 'Nose', true),
('J32.1', 'Chronic frontal sinusitis', 'Sinusitis frontal kronik', 'Nose', true),
('J32.2', 'Chronic ethmoidal sinusitis', 'Sinusitis etmoid kronik', 'Nose', true),
('J32.3', 'Chronic sphenoidal sinusitis', 'Sinusitis sfenoid kronik', 'Nose', true),
('J32.4', 'Chronic pansinusitis', 'Pansinusitis kronik', 'Nose', true),
('J32.8', 'Other chronic sinusitis', 'Sinusitis kronik lainnya', 'Nose', true),
('J32.9', 'Chronic sinusitis, unspecified', 'Sinusitis kronik tidak spesifik', 'Nose', true),
('J33.0', 'Polyp of nasal cavity', 'Polip kavum nasi', 'Nose', true),
('J33.1', 'Polypoid sinus degeneration', 'Degenerasi sinus polipoid', 'Nose', true),
('J33.8', 'Other polyp of sinus', 'Polip sinus lainnya', 'Nose', true),
('J33.9', 'Nasal polyp, unspecified', 'Polip hidung tidak spesifik', 'Nose', true),
('J34.0', 'Abscess, furuncle and carbuncle of nose', 'Abses, furunkel, dan karbunkel hidung', 'Nose', true),
('J34.1', 'Cyst and mucocele of nose and nasal sinus', 'Kista dan mukokel hidung dan sinus', 'Nose', true),
('J34.2', 'Deviated nasal septum', 'Deviasi septum nasi', 'Nose', true),
('J34.3', 'Hypertrophy of nasal turbinates', 'Hipertrofi konka nasi', 'Nose', true),
('J34.8', 'Other specified disorders of nose and nasal sinuses', 'Gangguan hidung dan sinus spesifik lainnya', 'Nose', true),
('J34.9', 'Disorder of nose and nasal sinuses, unspecified', 'Gangguan hidung dan sinus tidak spesifik', 'Nose', true),

-- Acute sinusitis
('J01.0', 'Acute maxillary sinusitis', 'Sinusitis maksilaris akut', 'Nose', true),
('J01.1', 'Acute frontal sinusitis', 'Sinusitis frontal akut', 'Nose', true),
('J01.2', 'Acute ethmoidal sinusitis', 'Sinusitis etmoid akut', 'Nose', true),
('J01.3', 'Acute sphenoidal sinusitis', 'Sinusitis sfenoid akut', 'Nose', true),
('J01.4', 'Acute pansinusitis', 'Pansinusitis akut', 'Nose', true),
('J01.8', 'Other acute sinusitis', 'Sinusitis akut lainnya', 'Nose', true),
('J01.9', 'Acute sinusitis, unspecified', 'Sinusitis akut tidak spesifik', 'Nose', true),
('J00', 'Acute nasopharyngitis (common cold)', 'Nasofaringitis akut (selesma)', 'Nose', true),

-- THROAT DISEASES (J02-J06, J35-J39)
-- Pharyngitis and tonsillitis
('J02.0', 'Streptococcal pharyngitis', 'Faringitis streptokokus', 'Throat', true),
('J02.8', 'Acute pharyngitis due to other specified organisms', 'Faringitis akut karena organisme lain', 'Throat', true),
('J02.9', 'Acute pharyngitis, unspecified', 'Faringitis akut tidak spesifik', 'Throat', true),
('J03.0', 'Streptococcal tonsillitis', 'Tonsilitis streptokokus', 'Throat', true),
('J03.8', 'Acute tonsillitis due to other specified organisms', 'Tonsilitis akut karena organisme lain', 'Throat', true),
('J03.9', 'Acute tonsillitis, unspecified', 'Tonsilitis akut tidak spesifik', 'Throat', true),
('J04.0', 'Acute laryngitis', 'Laringitis akut', 'Throat', true),
('J04.1', 'Acute tracheitis', 'Trakeitis akut', 'Throat', true),
('J04.2', 'Acute laryngotracheitis', 'Laringotrakeitis akut', 'Throat', true),
('J05.0', 'Acute obstructive laryngitis (croup)', 'Laringitis obstruktif akut (krup)', 'Throat', true),
('J05.1', 'Acute epiglottitis', 'Epiglotitis akut', 'Throat', true),
('J06.0', 'Acute laryngopharyngitis', 'Laringofaringitis akut', 'Throat', true),
('J06.8', 'Other acute upper respiratory infections', 'Infeksi saluran napas atas akut lainnya', 'Throat', true),
('J06.9', 'Acute upper respiratory infection, unspecified', 'Infeksi saluran napas atas akut tidak spesifik', 'Throat', true),

-- Chronic throat conditions
('J35.0', 'Chronic tonsillitis', 'Tonsilitis kronik', 'Throat', true),
('J35.1', 'Hypertrophy of tonsils', 'Hipertrofi tonsil', 'Throat', true),
('J35.2', 'Hypertrophy of adenoids', 'Hipertrofi adenoid', 'Throat', true),
('J35.3', 'Hypertrophy of tonsils with hypertrophy of adenoids', 'Hipertrofi tonsil dengan adenoid', 'Throat', true),
('J35.8', 'Other chronic diseases of tonsils and adenoids', 'Penyakit tonsil dan adenoid kronik lainnya', 'Throat', true),
('J35.9', 'Chronic disease of tonsils and adenoids, unspecified', 'Penyakit tonsil dan adenoid kronik tidak spesifik', 'Throat', true),
('J36', 'Peritonsillar abscess', 'Abses peritonsil', 'Throat', true),
('J37.0', 'Chronic laryngitis', 'Laringitis kronik', 'Throat', true),
('J37.1', 'Chronic laryngotracheitis', 'Laringotrakeitis kronik', 'Throat', true),
('J38.0', 'Paralysis of vocal cords and larynx', 'Paralisis pita suara dan laring', 'Throat', true),
('J38.1', 'Polyp of vocal cord and larynx', 'Polip pita suara dan laring', 'Throat', true),
('J38.2', 'Nodules of vocal cords', 'Nodul pita suara', 'Throat', true),
('J38.3', 'Other diseases of vocal cords', 'Penyakit pita suara lainnya', 'Throat', true),
('J38.4', 'Oedema of larynx', 'Edema laring', 'Throat', true),
('J38.5', 'Laryngeal spasm', 'Spasme laring', 'Throat', true),
('J38.6', 'Stenosis of larynx', 'Stenosis laring', 'Throat', true),
('J38.7', 'Other diseases of larynx', 'Penyakit laring lainnya', 'Throat', true),
('J39.0', 'Retropharyngeal and parapharyngeal abscess', 'Abses retrofaring dan parafaring', 'Throat', true),
('J39.1', 'Other abscess of pharynx', 'Abses faring lainnya', 'Throat', true),
('J39.2', 'Other diseases of pharynx', 'Penyakit faring lainnya', 'Throat', true),
('J39.3', 'Upper respiratory tract hypersensitivity reaction', 'Reaksi hipersensitivitas saluran napas atas', 'Throat', true),
('J39.8', 'Other specified diseases of upper respiratory tract', 'Penyakit saluran napas atas spesifik lainnya', 'Throat', true),
('J39.9', 'Disease of upper respiratory tract, unspecified', 'Penyakit saluran napas atas tidak spesifik', 'Throat', true),

-- Sleep disorders
('G47.3', 'Sleep apnoea', 'Apnea tidur', 'Throat', true),

-- Other common ENT-related conditions
('R04.0', 'Epistaxis', 'Epistaksis (mimisan)', 'Nose', true),
('R09.0', 'Asphyxia', 'Asfiksia', 'Throat', true),
('R09.1', 'Pleurisy', 'Pleuritis', 'Throat', true),
('R09.8', 'Other specified symptoms and signs involving respiratory system', 'Gejala sistem respirasi spesifik lainnya', 'Throat', true),
('R42', 'Dizziness and giddiness', 'Pusing dan vertigo', 'Ear', true),
('R43.0', 'Anosmia', 'Anosmia (hilang penciuman)', 'Nose', true),
('R43.1', 'Parosmia', 'Parosmia (gangguan penciuman)', 'Nose', true),
('R43.2', 'Parageusia', 'Parageusia (gangguan pengecapan)', 'Throat', true),
('R49.0', 'Dysphonia', 'Disfonia (gangguan suara)', 'Throat', true),
('R49.1', 'Aphonia', 'Afonia (hilang suara)', 'Throat', true),
('R49.2', 'Hypernasality and hyponasality', 'Hipernasalitas dan hiponasalitas', 'Throat', true),
('R51', 'Headache', 'Sakit kepala', 'General', true),
('T70.0', 'Otitic barotrauma', 'Barotrauma otik', 'Ear', true),
('T70.1', 'Sinus barotrauma', 'Barotrauma sinus', 'Nose', true)

ON CONFLICT (code) DO NOTHING;

-- Update service for ENT consultation if exists
INSERT INTO services (code, name, category, price, bpjs_price, is_active)
VALUES ('CONS_THT', 'Konsultasi Spesialis THT', 'consultation', 150000, 0, true)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  updated_at = NOW();
